spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.149.11:3306/gamedb?serverTimezone=Asia/Seoul
    username: root
    password: NGqsPBsg10v2DHLa
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/studydb?serverTimezone=Asia/Seoul
#    username: study
#    password: study

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
#      
#  messages:
#    basename: i18n/exception
#    encoding: UTF-8