spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///game-demo-db?cloudSqlInstance=learned-tube-276404:asia-northeast3:game-demo-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=NGqsPBsg10v2DHLa
#    username: root
#    password: NGqsPBsg10v2DHLa
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/studydb?serverTimezone=Asia/Seoul
#    username: study
#    password: study

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
#      
#  messages:
#    basename: i18n/exception
#    encoding: UTF-8